### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by dberntsson** [atrixiex/MMM-Pollenrapport#1]
I want to use this module and I'm missing documentation of how to use it.

**Comment by atrixiex** [comment]
Hi, sorry about that!
I've updated the readme with usage instructions, let me know if they work for you. This module has not yet been tested for the latest version of MagicMirror but should work.

**Comment by dberntsson** [comment]
Better! :) Thanks!

1. Is it possible to define what area of Sweden to get reports for?

2. And is it possible to filter pollen based on personal allergies?

**Comment by dberntsson** [comment]
Works fine on a MagicMirror2!
The only issue i found was the documented example configuration. It's missing , in the config block.
A recommended change would be to have a fully working example configuration and have inline comments defining the default values instead.

{
    module: 'MMM-Pollenrapport',
    position: 'position',
    config: {
        city: '94', //Optional. Default is 94
        updateInterval: 6*1000*60*60, //Optional. Default is 6 hours. In milliseconds. 6 * 1000 * 60 * 60
        itemsPerRow: 2 //Optional. Default 2. How many circles to show side by side before creating a new row of circles.
    }
},
